### ISSUE TITLE
XPATH

### ISSUE THREAD

**Issue by vanillamasonry** [neslib/Neslib.Xml#6]
Your code is awesome.
There is any plan for XPATH?

Thank you very much,
Paul

**Comment by erikvanbilsen** [comment]
There is currently no plan to add support for XPath since I don’t use if myself (and am not too familiar with it). I also like to keep the library small for now.

But I may consider adding support for it at some point if there are enough requests.

In the meantime, if you need XPath, then you can look at some of the other libraries in my [blog post](https://blog.grijjy.com/2020/10/07/an-xml-dom-with-just-8-bytes-per-node/).
